/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author android1
 */
public class CustomerInformation extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInformation
     */
    public CustomerInformation() {
        initComponents();

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        add_customer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        update_customer = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        customer_lists = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 0, 48)); // NOI18N
        jLabel1.setText("Customer Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 590, 86));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-customer-100.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 100, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 204, 255));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 160));

        add_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-customer-60.png"))); // NOI18N
        add_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_customerMouseClicked(evt);
            }
        });
        jPanel8.add(add_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 100));

        jLabel11.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(201, 62, 136));
        jLabel11.setText("Add Customer");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 190, 160));

        jPanel10.setBackground(new java.awt.Color(255, 204, 255));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 160));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(201, 62, 136));
        jLabel8.setText("Update");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        update_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-update-64.png"))); // NOI18N
        update_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_customerMouseClicked(evt);
            }
        });
        jPanel10.add(update_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 100));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, -1, 160));

        jPanel16.setBackground(new java.awt.Color(255, 204, 255));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 160));

        jLabel12.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(201, 62, 136));
        jLabel12.setText("Customers List");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        customer_lists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-customers-60.png"))); // NOI18N
        customer_lists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_lists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_listsMouseClicked(evt);
            }
        });
        jPanel16.add(customer_lists, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 100));

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, 160));

        back.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-48 (1).png"))); // NOI18N
        back.setText("Back");
        back.setBorder(new javax.swing.border.MatteBorder(null));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 550, 120, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer_inforamtion.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1310, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1310, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_customerMouseClicked
        // TODO add your handling code here:
        new UserAddCustomerInformation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_customerMouseClicked

    private void update_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_customerMouseClicked
        // TODO add your handling code here:
        new CustomerUpdate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update_customerMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Helper.Tools.setCenter(this);
    }//GEN-LAST:event_formWindowOpened

    private void customer_listsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_listsMouseClicked
        // TODO add your handling code here:

        new CustomerList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customer_listsMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:

        new Dashboard().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_customer;
    private javax.swing.JLabel back;
    private javax.swing.JLabel customer_lists;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel update_customer;
    // End of variables declaration//GEN-END:variables
}
