/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

/**
 *
 * @author android1
 */
public class CustomerUpdate extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAdd
     */
    public CustomerUpdate() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        searchID_txtfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        searchlbl_gif = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        customerName_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        confirmPassword_field = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radiobtn_male = new javax.swing.JRadioButton();
        radiobtn_female = new javax.swing.JRadioButton();
        update_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 144, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchID_txtfield.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        searchID_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchID_txtfieldActionPerformed(evt);
            }
        });
        jPanel2.add(searchID_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 330, 40));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search ID:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        searchlbl_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wired-outline-19-magnifier-zoom-search-hover-spin (1).gif"))); // NOI18N
        searchlbl_gif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlbl_gifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchlbl_gifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchlbl_gifMouseExited(evt);
            }
        });
        jPanel2.add(searchlbl_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 90, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 160));

        jPanel1.setBackground(new java.awt.Color(135, 47, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerName_field.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        customerName_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerName_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(customerName_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 330, 40));
        jPanel1.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 330, 40));
        jPanel1.add(confirmPassword_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 330, 40));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        email_field.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        jPanel1.add(email_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 330, 40));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        radiobtn_male.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        radiobtn_male.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_male.setText("Male");
        radiobtn_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(radiobtn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        radiobtn_female.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        radiobtn_female.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_female.setText("Female");
        radiobtn_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(radiobtn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        update_btn.setBackground(new java.awt.Color(255, 153, 153));
        update_btn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 160, 40));

        reset_btn.setBackground(new java.awt.Color(255, 102, 153));
        reset_btn.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 510, 710));

        jPanel4.setBackground(new java.awt.Color(135, 47, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1200, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Helper.Tools.setCenter(this);
        
    }//GEN-LAST:event_formWindowOpened

    private void customerName_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerName_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerName_fieldActionPerformed

    private void radiobtn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_femaleActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_reset_btnActionPerformed

    private void searchID_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchID_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchID_txtfieldActionPerformed

    private void searchlbl_gifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlbl_gifMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchlbl_gifMouseEntered

    private void searchlbl_gifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlbl_gifMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchlbl_gifMouseExited

    private void searchlbl_gifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlbl_gifMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchlbl_gifMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword_field;
    private javax.swing.JTextField customerName_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JRadioButton radiobtn_female;
    private javax.swing.JRadioButton radiobtn_male;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField searchID_txtfield;
    private javax.swing.JLabel searchlbl_gif;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
