/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author android1
 */
public class UserList extends javax.swing.JFrame {

    /**
     * Creates new form UserList
     */
    public UserList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        searchFieldbtn = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        Home_back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(UserTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, -1));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("User List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, -1));

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 110, -1));

        searchFieldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchFieldbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 250, -1));

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        Home_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-100.png"))); // NOI18N
        Home_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_backMouseClicked(evt);
            }
        });
        getContentPane().add(Home_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 110, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    Helper.Tools.setCenter(this);

    DAL d = new DAL();

    Object[][] result = d.select("SELECT user_id, username FROM users");
    String[] title = {"ID", "Username"};

    DefaultTableModel model = new DefaultTableModel(result, title);
    UserTable.setModel(model);
    }//GEN-LAST:event_formWindowOpened

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        
       Helper.Tools.setCenter(this);

    DAL d = new DAL();

    Object[][] result = d.select("SELECT user_id, username FROM users");
    String[] title = {"ID", "Username"};

    DefaultTableModel model = new DefaultTableModel(result, title);
    UserTable.setModel(model);
        
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // DELETE BUTTON IN USERLIST
        int selectedRow = UserTable.getSelectedRow();
    
    if (selectedRow == -1) {
        Helper.Tools.show("Please select a user to delete.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, "Are you sure you want to delete this user?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    // Get the user ID from the selected row
    Object userIdObj = UserTable.getValueAt(selectedRow, 0); // column 0 is user_id
    if (userIdObj == null) {
        Helper.Tools.show("User ID not found.");
        return;
    }

    int userId = Integer.parseInt(userIdObj.toString());

    // Delete from database
    DAL d = new DAL();
    boolean success = d.execute("DELETE FROM users WHERE user_id = " + userId);

    if (success) {
        Helper.Tools.show("User deleted successfully.");
        // Refresh the table
        Object[][] result = d.select("SELECT user_id, username FROM users");
        String[] title = {"ID", "Username"};
        UserTable.setModel(new javax.swing.table.DefaultTableModel(result, title));
    } else {
        Helper.Tools.show("Failed to delete user.");
    }
        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void searchFieldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldbtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void Home_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_backMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JLabel Home_back;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTable UserTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchFieldbtn;
    // End of variables declaration//GEN-END:variables
}
