/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;

import java.sql.*;
import org.mindrot.jbcrypt.BCrypt;


/**
 * @author android1
 */
public class UserAdd extends javax.swing.JFrame {

    /**
     * Creates new form UserAdd
     */
    public UserAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password_registeration_CNf = new javax.swing.JPasswordField();
        email_registration = new javax.swing.JTextField();
        password_registeration = new javax.swing.JPasswordField();
        username_registeration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radiobtn_female = new javax.swing.JRadioButton();
        radiobtn_male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btn_register_registeration = new javax.swing.JButton();
        btn_cancel_registeration = new javax.swing.JButton();
        UserAdd_back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wired-gradient-21-avatar-hover-jumping115.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 120, 140));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Back to Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));
        getContentPane().add(password_registeration_CNf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 330, 40));

        email_registration.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        getContentPane().add(email_registration, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 330, 40));
        getContentPane().add(password_registeration, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 330, 40));

        username_registeration.setFont(new java.awt.Font("Noto Sans", 1, 16)); // NOI18N
        username_registeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_registerationActionPerformed(evt);
            }
        });
        getContentPane().add(username_registeration, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 330, 40));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        buttonGroup1.add(radiobtn_female);
        radiobtn_female.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        radiobtn_female.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_female.setText("Female");
        radiobtn_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(radiobtn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, -1));

        buttonGroup1.add(radiobtn_male);
        radiobtn_male.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        radiobtn_male.setForeground(new java.awt.Color(255, 255, 255));
        radiobtn_male.setText("Male");
        radiobtn_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(radiobtn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        btn_register_registeration.setBackground(new java.awt.Color(255, 153, 153));
        btn_register_registeration.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btn_register_registeration.setForeground(new java.awt.Color(255, 255, 255));
        btn_register_registeration.setText("Register");
        btn_register_registeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_registerationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register_registeration, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 160, 40));

        btn_cancel_registeration.setBackground(new java.awt.Color(255, 102, 153));
        btn_cancel_registeration.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        btn_cancel_registeration.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel_registeration.setText("Cancel");
        btn_cancel_registeration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel_registerationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel_registeration, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 160, 40));

        UserAdd_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-100.png"))); // NOI18N
        UserAdd_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserAdd_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserAdd_backMouseClicked(evt);
            }
        });
        getContentPane().add(UserAdd_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 240, 140));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1170 x 720 Create  a new user.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        Helper.Tools.setCenter(this);
    }//GEN-LAST:event_formWindowOpened

    private void radiobtn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_femaleActionPerformed

    private void btn_cancel_registerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel_registerationActionPerformed
        // TODO add your handling code here:

        setVisible(false);
    }//GEN-LAST:event_btn_cancel_registerationActionPerformed

    private void btn_register_registerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_registerationActionPerformed
        // TODO add your handling code here:
        String username = username_registeration.getText().trim();
        String email = email_registration.getText().trim();
        String password = new String(password_registeration.getPassword());
        String confirmPassword = new String(password_registeration_CNf.getPassword());
        String gender = radiobtn_male.isSelected() ? "Male" : radiobtn_female.isSelected() ? "Female" : "";

        if (username.isEmpty() || email.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || gender.isEmpty()) {
            Helper.Tools.show("Please fill out all fields.");
            return;
        }

        if (!password.equals(confirmPassword)) {
            Helper.Tools.show("Passwords do not match!");
            return;
        }

        // Validate email format (check if email contains '@')
        if (!email.contains("@")) {
            Helper.Tools.show("Invalid email! Please enter a valid email address.");
            return;
        }

        DAL d = new DAL();
        try {
            PreparedStatement ps = d.getConnection().prepareStatement("SELECT * FROM users WHERE username = ?");
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Helper.Tools.show("Username already exists!");
            } else {
                String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());
                PreparedStatement insertPs = d.getConnection().prepareStatement("INSERT INTO users (username, password, email, gender) VALUES (?, ?, ?, ?)");
                insertPs.setString(1, username);
                insertPs.setString(2, hashedPassword);
                insertPs.setString(3, email);
                insertPs.setString(4, gender);

                int rowsAffected = insertPs.executeUpdate();
                if (rowsAffected > 0) {
                    Helper.Tools.show("Successfully created!");
                    setVisible(false);
                } else {
                    Helper.Tools.show("Error! Please try again.");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            Helper.Tools.show("An unexpected error occurred.");
        }
    }//GEN-LAST:event_btn_register_registerationActionPerformed

    private void username_registerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_registerationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_registerationActionPerformed

    private void UserAdd_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserAdd_backMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UserAdd_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserAdd_back;
    private javax.swing.JButton btn_cancel_registeration;
    private javax.swing.JButton btn_register_registeration;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField email_registration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField password_registeration;
    private javax.swing.JPasswordField password_registeration_CNf;
    private javax.swing.JRadioButton radiobtn_female;
    private javax.swing.JRadioButton radiobtn_male;
    private javax.swing.JTextField username_registeration;
    // End of variables declaration//GEN-END:variables
}
